### ISSUE TITLE
Tagline is not working.

### ISSUE THREAD

**Issue by hubutui** [damiencaselli/paperback#5]
[papaerback-demo](https://github.com/damiencaselli/paperback-demo/) set
```
Tagline = "Example site using gohugo Paperback theme"
```
But I could not get the expected effect on [paperback-demo](https://damiencaselli.github.io/paperback-demo/)

**Comment by meersau** [comment]
The check in layout was not all lowercase, which should be used for lookups.

Pull Request #6 created.

**Comment by ghost** [comment]
Closed by #6
